---
baseurl: "https://stelfox.net/"
languageCode: "en-US"
title: "Sam Stelfox"
author: "Sam Stelfox"
copyright: "2007-2017 Sam Stelfox. <a href='https://creativecommons.org/licenses/by/3.0/'>Some rights reserved</a>; Please attribute properly and link back."

metaDataFormat: "yaml"
paginate: 5

theme: "purity"

permalinks:
  blog: "/blog/:year/:month/:slug/"
  notes: "/notes/:slug/"

params:
  logo: "/img/logo.png"
  twitter: "https://twitter.com/SamStelfox"
  github: "https://github.com/sstelfox/"
  analytics: "UA-32188490-1"

menu:
  main:
    - Name: "Home"
      URL: "/"
      Weight: -50
    - Name: "About"
      URL: "/about"
      Weight: -30
    - Name: "Notes"
      URL: "/notes"
      Weight: -10
    - Name: "Blog Posts"
      URL: "/blog"
      Weight: -10
---
