---
baseurl: "https://stelfox.net/"
title: "The Elusive Stelfox"
languageCode: "en-US"
theme: "zen"
permalinks:
  blog: "/blog/:year/:month/:slug/"
paginate: 5
watch: true
twitter_name: SamStelfox
params:
  author: "Sam Stelfox"
  description: "My personal musings on security, events, programming, and computer systems."
---
