---
baseurl: "https://stelfox.net/"
title: "Thoughts From the Elusive Stelfox"
languageCode: "en-US"
theme: "casper"
permalinks:
  blog: "/blog/:year/:month/:slug/"
paginate: 10
watch: true
twitter_name: SamStelfox
params:
  author: "Sam Stelfox"
  description: "My personal musings on security, events, programming, and computer systems."
