---
baseURL: "https://stelfox.net"
title: "Sam Stelfox"
author:
  email: "sam@stelfox.net"
  name: "Sam Stelfox"

theme: "minimo"

googleAnalytics: "UA-32188490-1"

paginate: 10
preserveTaxonomyNames: true

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences: true

# Language Configuration
defaultContentLanguage: "en"
languageCode: "en-US"

params:
  assets:
    favicon: "favicon.ico"
    customCSS: [ "css/custom.css" ]
    customJS: [ "js/custom.js" ]
    gopher: "" # used in 404 template ( Generator: https://gopherize.me )
  copyright:
    prefix: ""
    holder: "Sam Stelfox"
    startYear: "2011"
    suffix: "- Content license information can be found on the <a rel='license' href='/licenses/'>licensing page</a>."
  info:
    description: "Thoughts from a software engineer, systems architect and Linux gubernāre."
    title404: "Nothing's here!"
  seo:
    # Title Separator: - – — · • * ⋆ | ~ « » < >
    titleSeparator: "•"
  settings:
    # date & time format: https://golang.org/pkg/time/
    dateFormat: "2006, Jan 02"
    listDateFormat: "2006, Jan 02"
    hideEntryNavigation: false
    hideSocialMenu: false
    showReadingTime: true
  social:
    email: "sam@stelfox.net"
    facebook: "sstelfox"
    github: "sstelfox"
    linkedin: "samstelfox"
    twitter: "SamStelfox"
    keybase: "sstelfox"
    config:
      #platforms: ["github","facebook","twitter","instagram","email","codepen","linkedin"]
      platforms: [ "email", "github", "twitter", "keybase", "facebook", "linkedin" ]

taxonomies:
  category: "categories"
  tag: "tags"

permalinks:
  notes: "/notes/:slug"
  page: "/:slug/"
  posts: "/posts/:year/:month/:slug/"

blackfriday:
  hrefTargetBlank: true

languages:
  # edit this block for your own language
  en:
    lang: "en"
    languageName: "English"
    weight: 1
