---
baseurl: "https://stelfox.net/"
languageCode: "en-US"
title: "The Elusive Stelfox"
author: "Sam Stelfox"
copyright: "Sam Stelfox. All rights reserved."

disableHugoGeneratorInject: true
metaDataFormat: "yaml"
paginate: 5

theme: "detox"

permalinks:
  blog: "/blog/:year/:month/:slug/"
  notes: "/notes/:slug/"

params:
  logo: "/img/logo.png"
  twitter: "https://twitter.com/SamStelfox"
  github: "https://github.com/sstelfox/"
  analytics: "UA-32188490-1"
---
