name = "Purity"
license = "Private"
licenselink = "https://github.com/sstelfox/stelfox.net/blob/rework/themes/purity/LICENSE.md"
description = ""
homepage = "https://stelfox.net"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Sam Stelfox"
  homepage = "https://stelfox.net"
